services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

  events_service:
    build:
      context: ./events_service
      dockerfile: Dockerfile
    ports:
      - "${ARTICLES_SERVICE_PORT}:8001"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
