services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Deshabilita la seguridad
      - xpack.security.transport.ssl.enabled=false  # Deshabilita SSL
    ports:
      - "9200:9200"
    networks:
      - backend

networks:
  backend:
    driver: bridge
